// Represents a standardized structure for detailed error information, often used in HTTP APIs.
// See RFC 9457: https://datatracker.ietf.org/doc/html/rfc9457
export interface ProblemDetails<TError = unknown> {
  /**
   * A URI reference that identifies the problem type.
   */
  type?: string;
  /**
   * A short, human-readable summary of the problem type.
   */
  title?: string;
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status?: number;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * A unique identifier for tracing the request (often used for logging and debugging).
   */
  traceId?: string;
  /**
   * A map of error details, typically used for validation errors.
   */
  errors?: Record<string, TError>;
}
