site_name: Simple State Management
theme:
  name: material
  logo: assets/images/logo.png
  features:
    - navigation.expand
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - css/overrides.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - glightbox
  - include-markdown
nav:
  - index.md
  - Concepts:
    - state.md
  - Libraries:
    - libraries/ngssm-store-caching.md
    - ngssm-data:
      - libraries/ngssm-data.md
      - libraries/ngssm-data-simple-use-case.md
    - libraries/ngssm-toolkit.md
